client_config_backend: settings
client_config:
  client_id: 438939410934-6a62fi08egb3cuhp75bc33gl6act9cqk.apps.googleusercontent.com
  client_secret: SytNtXB16jWx7WmzgWQhgkvD

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install